import { teams, pitchTypes, weatherTypes, fieldSettings, battingIntents, bowlingPlans } from './data.js';
import { createMatchState, simulateBall, currentRunRate } from './engine.js';

const app = document.getElementById('app');
let game = { stage:'home', selectedTeam:null, opponent:null, xi:[], captain:null, keeper:null, bowling:[], toss:null, match:null, timer:null };

function render(){
  if (game.stage==='home') return renderHome();
  if (game.stage==='squad') return renderSquad();
  if (game.stage==='preview') return renderPreview();
  if (game.stage==='toss') return renderToss();
  if (game.stage==='live') return renderLive();
  if (game.stage==='result') return renderResult();
}

function renderHome(){ app.innerHTML = `<div class="screen"><h1>Cricket Manager Elite</h1><p>Choose your franchise</p><div class="grid">${teams.map(t=>`<article class="team" style="--c:${t.color}"><h3>${t.name}</h3><p>Rating ${t.rating}</p><p>⭐ ${t.star}</p><small>+ ${t.strengths}</small><small>- ${t.weaknesses}</small><button data-id="${t.id}">Select Team</button></article>`).join('')}</div></div>`; app.querySelectorAll('button').forEach(b=>b.onclick=()=>{ game.selectedTeam=teams.find(t=>t.id===b.dataset.id); game.opponent=teams.find(t=>t.id!==b.dataset.id); game.stage='squad'; render(); }); }
function renderSquad(){ const p=game.selectedTeam.players; app.innerHTML = `<div class="screen"><h2>${game.selectedTeam.name} Squad Setup</h2><p>Select XI, captain, wicketkeeper, and 5 bowling options.</p><div class="grid players">${p.map(x=>card(x)).join('')}</div><div class="cta"><button id="auto">Auto XI</button><button id="next">Continue to Match Preview</button></div></div>`; app.querySelectorAll('.pick').forEach(c=>c.onchange=updatePicks); app.querySelectorAll('.captain').forEach(c=>c.onchange=e=> game.captain=Number(e.target.value)); app.querySelectorAll('.keeper').forEach(c=>c.onchange=e=> game.keeper=Number(e.target.value)); document.getElementById('auto').onclick=()=>{ game.xi=[...p].sort((a,b)=>b.battingSkill+b.bowlingSkill-(a.battingSkill+a.bowlingSkill)).slice(0,7); game.xi=[...p]; game.bowling=[...p].sort((a,b)=>b.bowlingSkill-a.bowlingSkill).slice(0,5); game.captain=game.xi[0].id; game.keeper=game.xi.find(x=>x.role==='Wicketkeeper')?.id || game.xi[0].id; game.stage='preview'; render(); }; document.getElementById('next').onclick=()=>{ if(!validateSquad()) return alert('Set XI (at least 7 in demo), captain, keeper, and 5 bowlers.'); game.stage='preview'; render(); }; }
function card(x){ return `<article class="player"><h4>${x.name}</h4><p>${x.role} • ${x.cricketRole}</p><div class="badges"><span>BAT ${x.battingSkill}</span><span>BWL ${x.bowlingSkill}</span><span>FIT ${x.fitness}</span><span>FORM ${x.form}</span><span>CONF ${x.confidence}</span></div><small>${x.specialTraits.join(', ')}</small><div class="opts"><label><input class="pick" data-id="${x.id}" type="checkbox"> XI</label><label><input class="captain" name="cap" type="radio" value="${x.id}"> C</label><label><input class="keeper" name="wk" type="radio" value="${x.id}"> WK</label><label><input class="bowl" data-id="${x.id}" type="checkbox"> Bowl</label></div></article>`; }
function updatePicks(){ const p=game.selectedTeam.players; game.xi = p.filter(x=>document.querySelector(`.pick[data-id='${x.id}']`)?.checked); game.bowling = p.filter(x=>document.querySelector(`.bowl[data-id='${x.id}']`)?.checked).slice(0,5); }
function validateSquad(){ updatePicks(); return game.xi.length>=7 && game.captain && game.keeper && game.bowling.length>=3; }
function renderPreview(){ const pitch = pitchTypes[Math.floor(Math.random()*pitchTypes.length)], weather = weatherTypes[Math.floor(Math.random()*weatherTypes.length)]; game.toss={pitch,weather}; app.innerHTML=`<div class="screen"><h2>Match Preview</h2><div class="panel"><p>Venue: Neon Cricket Dome</p><p>Pitch: <b>${pitch}</b></p><p>Weather: <b>${weather}</b></p><p>Key battle: ${game.selectedTeam.star} vs ${game.opponent.star}</p><p>Win probability: ${52 + Math.floor(Math.random()*10)}%</p></div><button id="toss">Go to Toss</button></div>`; document.getElementById('toss').onclick=()=>{game.stage='toss'; render();}; }
function renderToss(){ app.innerHTML=`<div class="screen"><h2>Cinematic Toss</h2><div class="coin" id="coin">🪙</div><div class="cta"><button data-call="Heads">Heads</button><button data-call="Tails">Tails</button></div><div id="tossResult"></div></div>`; app.querySelectorAll('[data-call]').forEach(b=>b.onclick=()=>runToss(b.dataset.call)); }
function runToss(call){ const flip = Math.random()<0.5?'Heads':'Tails'; const win = call===flip; const aiDecision = (game.toss.pitch.includes('Green')||game.toss.weather==='Cloudy')?'Bowl':'Bat'; const decision = win ? prompt('You won toss! Type Bat or Bowl','Bat') || 'Bat' : aiDecision; game.toss = {...game.toss, call, flip, winner: win?game.selectedTeam.name:game.opponent.name, decision}; document.getElementById('tossResult').innerHTML=`<p>${flip}! ${game.toss.winner} won toss and chose to ${decision} first.</p><button id='start'>Start Match</button>`; document.getElementById('start').onclick=()=>{startMatch();}; }
function startMatch(){ const home={name:game.selectedTeam.name, xi:game.xi, bowling:game.bowling}; const away={name:game.opponent.name, xi:game.opponent.players, bowling:[...game.opponent.players].sort((a,b)=>b.bowlingSkill-a.bowlingSkill).slice(0,5)}; game.match = createMatchState(home, away, { toss:game.toss }); game.stage='live'; render(); tick(); }
function tick(){ if(game.stage!=='live') return; const i=game.match.innings; if(i.balls>=game.match.maxBalls || i.wkts>=10){ game.stage='result'; render(); return; } simulateBall(game.match); renderLiveData(); game.timer=setTimeout(tick,750); }
function renderLive(){ app.innerHTML=`<div class="screen"><h2>Live Match Dashboard</h2><div class="live"><section class="panel score"><h1 id='score'>0/0</h1><p id='meta'>0.0 overs</p><div class='bars'><label>Momentum <progress id='mom' max='100' value='50'></progress></label><label>Win Prob <progress id='wp' max='100' value='50'></progress></label></div><div id='recent' class='chips'></div></section><section class='panel'><h3>Tactics</h3><select id='batIntent'>${battingIntents.map(x=>`<option>${x}</option>`).join('')}</select><select id='bowlPlan'>${bowlingPlans.map(x=>`<option>${x}</option>`).join('')}</select><select id='field'>${fieldSettings.map(x=>`<option>${x}</option>`).join('')}</select><button id='pause'>Pause</button><button id='resume'>Resume</button></section><section class='panel'><h3>Commentary</h3><div id='comm' class='feed'></div></section></div></div>`; document.getElementById('batIntent').onchange=e=>game.match.battingIntent=e.target.value; document.getElementById('bowlPlan').onchange=e=>game.match.bowlingPlan=e.target.value; document.getElementById('field').onchange=e=>game.match.fieldSetting=e.target.value; document.getElementById('pause').onclick=()=>clearTimeout(game.timer); document.getElementById('resume').onclick=()=>tick(); renderLiveData(); }
function renderLiveData(){ if(game.stage!=='live') return; const i=game.match.innings; document.getElementById('score').textContent=`${i.runs}/${i.wkts}`; document.getElementById('meta').textContent=`${Math.floor(i.balls/6)}.${i.balls%6} overs • CRR ${currentRunRate(game.match).toFixed(2)}`; document.getElementById('mom').value=i.momentum; document.getElementById('wp').value=i.winProb; document.getElementById('recent').innerHTML=i.recent.map(b=>`<span>${b}</span>`).join(''); document.getElementById('comm').innerHTML=i.commentary.map(c=>`<p>${c}</p>`).join(''); }
function renderResult(){ const i=game.match.innings; app.innerHTML=`<div class='screen'><h2>Match Result</h2><div class='panel'><h1>${game.selectedTeam.name} ${i.runs}/${i.wkts}</h1><p>Completed in ${Math.floor(i.balls/6)}.${i.balls%6} overs</p><p>Player of the Match: ${game.match.home.xi.sort((a,b)=>b.battingSkill-a.battingSkill)[0].name}</p><p>Turning point: ${i.commentary.find(x=>x.includes('WICKET'))||'Late over pressure'}</p><button id='again'>Play Again</button></div></div>`; document.getElementById('again').onclick=()=>{clearTimeout(game.timer); game={...game, stage:'home', match:null}; render();}; }

render();
